export interface ElementData {
  number: number;
  symbol: string;
  name: string;
  mass: number;
  category:
    | 'reactive-nonmetal'
    | 'noble-gas'
    | 'alkali-metal'
    | 'alkaline-earth'
    | 'metalloid'
    | 'post-transition-metal'
    | 'transition-metal'
    | 'lanthanide'
    | 'actinide'
    | 'synthetic';
  group: number; // 1 to 18 (0 for Lanthanides/Actinides)
  period: number; // 1 to 7
  state: 'Gas' | 'Liquid' | 'Solid' | 'Synthetic';
  config: string;
  
  // High-fidelity details requested by the user
  groupType: 'metal' | 'metalloid' | 'nonmetal';
  oxidationStates?: string;
  electronegativity?: number;
  atomicRadius?: string; // e.g. "120 pm"
  ionizationEnergy?: string; // e.g. "13.598 eV"
  electronAffinity?: string; // e.g. "0.754 eV"
  meltingPoint?: string; // e.g. "13.81 K"
  boilingPoint?: string; // e.g. "20.28 K"
  density?: string; // e.g. "0.00008988 g/cm³"
  yearDiscovered?: string; // e.g. "1766" or "Ancient"
}

export const PERIODIC_ELEMENTS: ElementData[] = [
  // --- PERIOD 1 (2 elements) ---
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    mass: 1.008,
    category: 'reactive-nonmetal',
    group: 1,
    period: 1,
    state: 'Gas',
    config: '1s¹',
    groupType: 'nonmetal',
    oxidationStates: '+1, -1',
    electronegativity: 2.2,
    atomicRadius: '120 pm',
    ionizationEnergy: '13.598 eV',
    electronAffinity: '0.754 eV',
    meltingPoint: '13.81 K',
    boilingPoint: '20.28 K',
    density: '0.00008988 g/cm³',
    yearDiscovered: '1766'
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    mass: 4.0026,
    category: 'noble-gas',
    group: 18,
    period: 1,
    state: 'Gas',
    config: '1s²',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 4.0, // Pauling scale equivalent
    atomicRadius: '140 pm',
    ionizationEnergy: '24.587 eV',
    electronAffinity: '-0.078 eV',
    meltingPoint: '0.95 K',
    boilingPoint: '4.22 K',
    density: '0.0001785 g/cm³',
    yearDiscovered: '1868'
  },

  // --- PERIOD 2 (8 elements) ---
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    mass: 6.94,
    category: 'alkali-metal',
    group: 1,
    period: 2,
    state: 'Solid',
    config: '[He] 2s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 0.98,
    atomicRadius: '182 pm',
    ionizationEnergy: '5.392 eV',
    electronAffinity: '0.618 eV',
    meltingPoint: '453.69 K',
    boilingPoint: '1615 K',
    density: '0.534 g/cm³',
    yearDiscovered: '1817'
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    mass: 9.0122,
    category: 'alkaline-earth',
    group: 2,
    period: 2,
    state: 'Solid',
    config: '[He] 2s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 1.57,
    atomicRadius: '153 pm',
    ionizationEnergy: '9.323 eV',
    electronAffinity: '-0.518 eV',
    meltingPoint: '1560 K',
    boilingPoint: '2742 K',
    density: '1.85 g/cm³',
    yearDiscovered: '1798'
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    mass: 10.81,
    category: 'metalloid',
    group: 13,
    period: 2,
    state: 'Solid',
    config: '[He] 2s² 2p¹',
    groupType: 'metalloid',
    oxidationStates: '+3',
    electronegativity: 2.04,
    atomicRadius: '192 pm',
    ionizationEnergy: '8.298 eV',
    electronAffinity: '0.279 eV',
    meltingPoint: '2349 K',
    boilingPoint: '4200 K',
    density: '2.34 g/cm³',
    yearDiscovered: '1808'
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    mass: 12.011,
    category: 'reactive-nonmetal',
    group: 14,
    period: 2,
    state: 'Solid',
    config: '[He] 2s² 2p²',
    groupType: 'nonmetal',
    oxidationStates: '+4, +3, +2, +1, -4',
    electronegativity: 2.55,
    atomicRadius: '170 pm',
    ionizationEnergy: '11.260 eV',
    electronAffinity: '1.263 eV',
    meltingPoint: '3800 K',
    boilingPoint: '4300 K',
    density: '2.267 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    mass: 14.007,
    category: 'reactive-nonmetal',
    group: 15,
    period: 2,
    state: 'Gas',
    config: '[He] 2s² 2p³',
    groupType: 'nonmetal',
    oxidationStates: '+5, +4, +3, +2, +1, -3',
    electronegativity: 3.04,
    atomicRadius: '155 pm',
    ionizationEnergy: '14.534 eV',
    electronAffinity: '-0.073 eV',
    meltingPoint: '63.15 K',
    boilingPoint: '77.36 K',
    density: '0.0012506 g/cm³',
    yearDiscovered: '1772'
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    mass: 15.999,
    category: 'reactive-nonmetal',
    group: 16,
    period: 2,
    state: 'Gas',
    config: '[He] 2s² 2p⁴',
    groupType: 'nonmetal',
    oxidationStates: '-2, -1',
    electronegativity: 3.44,
    atomicRadius: '152 pm',
    ionizationEnergy: '13.618 eV',
    electronAffinity: '1.461 eV',
    meltingPoint: '54.36 K',
    boilingPoint: '90.20 K',
    density: '0.001429 g/cm³',
    yearDiscovered: '1774'
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    mass: 18.998,
    category: 'reactive-nonmetal',
    group: 17,
    period: 2,
    state: 'Gas',
    config: '[He] 2s² 2p⁵',
    groupType: 'nonmetal',
    oxidationStates: '-1',
    electronegativity: 3.98,
    atomicRadius: '147 pm',
    ionizationEnergy: '17.423 eV',
    electronAffinity: '3.399 eV',
    meltingPoint: '53.53 K',
    boilingPoint: '85.03 K',
    density: '0.001696 g/cm³',
    yearDiscovered: '1886'
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    mass: 20.180,
    category: 'noble-gas',
    group: 18,
    period: 2,
    state: 'Gas',
    config: '[He] 2s² 2p⁶',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 4.4,
    atomicRadius: '154 pm',
    ionizationEnergy: '21.565 eV',
    electronAffinity: '-1.15 eV',
    meltingPoint: '24.56 K',
    boilingPoint: '27.07 K',
    density: '0.0008999 g/cm³',
    yearDiscovered: '1898'
  },

  // --- PERIOD 3 (8 elements) ---
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    mass: 22.990,
    category: 'alkali-metal',
    group: 1,
    period: 3,
    state: 'Solid',
    config: '[Ne] 3s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 0.93,
    atomicRadius: '227 pm',
    ionizationEnergy: '5.139 eV',
    electronAffinity: '0.548 eV',
    meltingPoint: '370.87 K',
    boilingPoint: '1156 K',
    density: '0.971 g/cm³',
    yearDiscovered: '1807'
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    mass: 24.305,
    category: 'alkaline-earth',
    group: 2,
    period: 3,
    state: 'Solid',
    config: '[Ne] 3s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 1.31,
    atomicRadius: '173 pm',
    ionizationEnergy: '7.646 eV',
    electronAffinity: '-0.42 eV',
    meltingPoint: '923 K',
    boilingPoint: '1363 K',
    density: '1.738 g/cm³',
    yearDiscovered: '1755'
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminium',
    mass: 26.982,
    category: 'post-transition-metal',
    group: 13,
    period: 3,
    state: 'Solid',
    config: '[Ne] 3s² 3p¹',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.61,
    atomicRadius: '184 pm',
    ionizationEnergy: '5.986 eV',
    electronAffinity: '0.441 eV',
    meltingPoint: '933.47 K',
    boilingPoint: '2792 K',
    density: '2.70 g/cm³',
    yearDiscovered: '1825'
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    mass: 28.085,
    category: 'metalloid',
    group: 14,
    period: 3,
    state: 'Solid',
    config: '[Ne] 3s² 3p²',
    groupType: 'metalloid',
    oxidationStates: '+4, -4',
    electronegativity: 1.9,
    atomicRadius: '210 pm',
    ionizationEnergy: '8.152 eV',
    electronAffinity: '1.385 eV',
    meltingPoint: '1687 K',
    boilingPoint: '3538 K',
    density: '2.329 g/cm³',
    yearDiscovered: '1823'
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    mass: 30.974,
    category: 'reactive-nonmetal',
    group: 15,
    period: 3,
    state: 'Solid',
    config: '[Ne] 3s² 3p³',
    groupType: 'nonmetal',
    oxidationStates: '+5, +3, -3',
    electronegativity: 2.19,
    atomicRadius: '180 pm',
    ionizationEnergy: '10.487 eV',
    electronAffinity: '0.746 eV',
    meltingPoint: '317.30 K',
    boilingPoint: '553.60 K',
    density: '1.823 g/cm³',
    yearDiscovered: '1669'
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    mass: 32.06,
    category: 'reactive-nonmetal',
    group: 16,
    period: 3,
    state: 'Solid',
    config: '[Ne] 3s² 3p⁴',
    groupType: 'nonmetal',
    oxidationStates: '+6, +4, -2',
    electronegativity: 2.58,
    atomicRadius: '180 pm',
    ionizationEnergy: '10.360 eV',
    electronAffinity: '2.077 eV',
    meltingPoint: '388.36 K',
    boilingPoint: '717.80 K',
    density: '2.07 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    mass: 35.45,
    category: 'reactive-nonmetal',
    group: 17,
    period: 3,
    state: 'Gas',
    config: '[Ne] 3s² 3p⁵',
    groupType: 'nonmetal',
    oxidationStates: '+7, +5, +3, +1, -1',
    electronegativity: 3.16,
    atomicRadius: '175 pm',
    ionizationEnergy: '12.968 eV',
    electronAffinity: '3.617 eV',
    meltingPoint: '171.60 K',
    boilingPoint: '239.11 K',
    density: '0.003214 g/cm³',
    yearDiscovered: '1774'
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    mass: 39.948,
    category: 'noble-gas',
    group: 18,
    period: 3,
    state: 'Gas',
    config: '[Ne] 3s² 3p⁶',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 3.2,
    atomicRadius: '188 pm',
    ionizationEnergy: '15.760 eV',
    electronAffinity: '-0.96 eV',
    meltingPoint: '83.80 K',
    boilingPoint: '87.30 K',
    density: '0.001784 g/cm³',
    yearDiscovered: '1894'
  },

  // --- PERIOD 4 (18 elements) ---
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    mass: 39.098,
    category: 'alkali-metal',
    group: 1,
    period: 4,
    state: 'Solid',
    config: '[Ar] 4s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 0.82,
    atomicRadius: '275 pm',
    ionizationEnergy: '4.341 eV',
    electronAffinity: '0.501 eV',
    meltingPoint: '336.50 K',
    boilingPoint: '1032 K',
    density: '0.89 g/cm³',
    yearDiscovered: '1807'
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    mass: 40.078,
    category: 'alkaline-earth',
    group: 2,
    period: 4,
    state: 'Solid',
    config: '[Ar] 4s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 1.0,
    atomicRadius: '231 pm',
    ionizationEnergy: '6.113 eV',
    electronAffinity: '-0.02 eV',
    meltingPoint: '1115 K',
    boilingPoint: '1757 K',
    density: '1.54 g/cm³',
    yearDiscovered: '1808'
  },
  {
    number: 21,
    symbol: 'Sc',
    name: 'Scandium',
    mass: 44.956,
    category: 'transition-metal',
    group: 3,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹ 4s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.36,
    atomicRadius: '211 pm',
    ionizationEnergy: '6.561 eV',
    electronAffinity: '0.188 eV',
    meltingPoint: '1814 K',
    boilingPoint: '3109 K',
    density: '2.989 g/cm³',
    yearDiscovered: '1879'
  },
  {
    number: 22,
    symbol: 'Ti',
    name: 'Titanium',
    mass: 47.867,
    category: 'transition-metal',
    group: 4,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d² 4s²',
    groupType: 'metal',
    oxidationStates: '+4, +3',
    electronegativity: 1.54,
    atomicRadius: '187 pm',
    ionizationEnergy: '6.828 eV',
    electronAffinity: '0.079 eV',
    meltingPoint: '1941 K',
    boilingPoint: '3560 K',
    density: '4.506 g/cm³',
    yearDiscovered: '1791'
  },
  {
    number: 23,
    symbol: 'V',
    name: 'Vanadium',
    mass: 50.942,
    category: 'transition-metal',
    group: 5,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d³ 4s²',
    groupType: 'metal',
    oxidationStates: '+5, +4, +3, +2',
    electronegativity: 1.63,
    atomicRadius: '179 pm',
    ionizationEnergy: '6.746 eV',
    electronAffinity: '0.526 eV',
    meltingPoint: '2183 K',
    boilingPoint: '3680 K',
    density: '6.11 g/cm³',
    yearDiscovered: '1801'
  },
  {
    number: 24,
    symbol: 'Cr',
    name: 'Chromium',
    mass: 51.996,
    category: 'transition-metal',
    group: 6,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d⁵ 4s¹',
    groupType: 'metal',
    oxidationStates: '+6, +3, +2',
    electronegativity: 1.66,
    atomicRadius: '189 pm',
    ionizationEnergy: '6.767 eV',
    electronAffinity: '0.676 eV',
    meltingPoint: '2180 K',
    boilingPoint: '2944 K',
    density: '7.19 g/cm³',
    yearDiscovered: '1797'
  },
  {
    number: 25,
    symbol: 'Mn',
    name: 'Manganese',
    mass: 54.938,
    category: 'transition-metal',
    group: 7,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d⁵ 4s²',
    groupType: 'metal',
    oxidationStates: '+7, +6, +4, +2, +3',
    electronegativity: 1.55,
    atomicRadius: '197 pm',
    ionizationEnergy: '7.434 eV',
    electronAffinity: '-0.5 eV',
    meltingPoint: '1519 K',
    boilingPoint: '2334 K',
    density: '7.21 g/cm³',
    yearDiscovered: '1774'
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    mass: 55.845,
    category: 'transition-metal',
    group: 8,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d⁶ 4s²',
    groupType: 'metal',
    oxidationStates: '+3, +2, +6',
    electronegativity: 1.83,
    atomicRadius: '194 pm',
    ionizationEnergy: '7.902 eV',
    electronAffinity: '0.151 eV',
    meltingPoint: '1811 K',
    boilingPoint: '3134 K',
    density: '7.874 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 27,
    symbol: 'Co',
    name: 'Cobalt',
    mass: 58.933,
    category: 'transition-metal',
    group: 9,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d⁷ 4s²',
    groupType: 'metal',
    oxidationStates: '+3, +2',
    electronegativity: 1.88,
    atomicRadius: '192 pm',
    ionizationEnergy: '7.881 eV',
    electronAffinity: '0.662 eV',
    meltingPoint: '1768 K',
    boilingPoint: '3200 K',
    density: '8.90 g/cm³',
    yearDiscovered: '1735'
  },
  {
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    mass: 58.693,
    category: 'transition-metal',
    group: 10,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d⁸ 4s²',
    groupType: 'metal',
    oxidationStates: '+2, +3',
    electronegativity: 1.91,
    atomicRadius: '163 pm',
    ionizationEnergy: '7.640 eV',
    electronAffinity: '1.157 eV',
    meltingPoint: '1728 K',
    boilingPoint: '3186 K',
    density: '8.908 g/cm³',
    yearDiscovered: '1751'
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    mass: 63.546,
    category: 'transition-metal',
    group: 11,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹⁰ 4s¹',
    groupType: 'metal',
    oxidationStates: '+2, +1',
    electronegativity: 1.9,
    atomicRadius: '140 pm',
    ionizationEnergy: '7.726 eV',
    electronAffinity: '1.228 eV',
    meltingPoint: '1357.77 K',
    boilingPoint: '2835 K',
    density: '8.96 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    mass: 65.38,
    category: 'transition-metal',
    group: 12,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹⁰ 4s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 1.65,
    atomicRadius: '139 pm',
    ionizationEnergy: '9.394 eV',
    electronAffinity: '-0.43 eV',
    meltingPoint: '692.68 K',
    boilingPoint: '1180 K',
    density: '7.14 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 31,
    symbol: 'Ga',
    name: 'Gallium',
    mass: 69.723,
    category: 'post-transition-metal',
    group: 13,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹⁰ 4s² 4p¹',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.81,
    atomicRadius: '187 pm',
    ionizationEnergy: '5.999 eV',
    electronAffinity: '0.43 eV',
    meltingPoint: '302.91 K',
    boilingPoint: '2673 K',
    density: '5.91 g/cm³',
    yearDiscovered: '1875'
  },
  {
    number: 32,
    symbol: 'Ge',
    name: 'Germanium',
    mass: 72.63,
    category: 'metalloid',
    group: 14,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹⁰ 4s² 4p²',
    groupType: 'metalloid',
    oxidationStates: '+4, +2',
    electronegativity: 2.01,
    atomicRadius: '211 pm',
    ionizationEnergy: '7.900 eV',
    electronAffinity: '1.233 eV',
    meltingPoint: '1211.40 K',
    boilingPoint: '3106 K',
    density: '5.323 g/cm³',
    yearDiscovered: '1886'
  },
  {
    number: 33,
    symbol: 'As',
    name: 'Arsenic',
    mass: 74.922,
    category: 'metalloid',
    group: 15,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹⁰ 4s² 4p³',
    groupType: 'metalloid',
    oxidationStates: '+5, +3, -3',
    electronegativity: 2.18,
    atomicRadius: '185 pm',
    ionizationEnergy: '9.815 eV',
    electronAffinity: '0.81 eV',
    meltingPoint: '1090 K',
    boilingPoint: '887 K',
    density: '5.727 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 34,
    symbol: 'Se',
    name: 'Selenium',
    mass: 78.971,
    category: 'reactive-nonmetal',
    group: 16,
    period: 4,
    state: 'Solid',
    config: '[Ar] 3d¹⁰ 4s² 4p⁴',
    groupType: 'nonmetal',
    oxidationStates: '+6, +4, -2',
    electronegativity: 2.55,
    atomicRadius: '190 pm',
    ionizationEnergy: '9.752 eV',
    electronAffinity: '2.021 eV',
    meltingPoint: '494 K',
    boilingPoint: '958 K',
    density: '4.81 g/cm³',
    yearDiscovered: '1817'
  },
  {
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    mass: 79.904,
    category: 'reactive-nonmetal',
    group: 17,
    period: 4,
    state: 'Liquid',
    config: '[Ar] 3d¹⁰ 4s² 4p⁵',
    groupType: 'nonmetal',
    oxidationStates: '+5, +1, -1',
    electronegativity: 2.96,
    atomicRadius: '185 pm',
    ionizationEnergy: '11.814 eV',
    electronAffinity: '3.365 eV',
    meltingPoint: '265.80 K',
    boilingPoint: '332 K',
    density: '3.12 g/cm³',
    yearDiscovered: '1826'
  },
  {
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    mass: 83.798,
    category: 'noble-gas',
    group: 18,
    period: 4,
    state: 'Gas',
    config: '[Ar] 3d¹⁰ 4s² 4p⁶',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 3.0,
    atomicRadius: '202 pm',
    ionizationEnergy: '14.000 eV',
    electronAffinity: '-0.96 eV',
    meltingPoint: '115.79 K',
    boilingPoint: '119.93 K',
    density: '0.003733 g/cm³',
    yearDiscovered: '1898'
  },

  // --- PERIOD 5 (18 elements) ---
  {
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    mass: 85.468,
    category: 'alkali-metal',
    group: 1,
    period: 5,
    state: 'Solid',
    config: '[Kr] 5s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 0.82,
    atomicRadius: '303 pm',
    ionizationEnergy: '4.177 eV',
    electronAffinity: '0.486 eV',
    meltingPoint: '312.46 K',
    boilingPoint: '961 K',
    density: '1.532 g/cm³',
    yearDiscovered: '1861'
  },
  {
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    mass: 87.62,
    category: 'alkaline-earth',
    group: 2,
    period: 5,
    state: 'Solid',
    config: '[Kr] 5s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 0.95,
    atomicRadius: '249 pm',
    ionizationEnergy: '5.695 eV',
    electronAffinity: '0.052 eV',
    meltingPoint: '1050 K',
    boilingPoint: '1655 K',
    density: '2.64 g/cm³',
    yearDiscovered: '1790'
  },
  {
    number: 39,
    symbol: 'Y',
    name: 'Yttrium',
    mass: 88.906,
    category: 'transition-metal',
    group: 3,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹ 5s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.22,
    atomicRadius: '219 pm',
    ionizationEnergy: '6.217 eV',
    electronAffinity: '0.307 eV',
    meltingPoint: '1799 K',
    boilingPoint: '3609 K',
    density: '4.472 g/cm³',
    yearDiscovered: '1794'
  },
  {
    number: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    mass: 91.224,
    category: 'transition-metal',
    group: 4,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d² 5s²',
    groupType: 'metal',
    oxidationStates: '+4',
    electronegativity: 1.33,
    atomicRadius: '186 pm',
    ionizationEnergy: '6.634 eV',
    electronAffinity: '0.426 eV',
    meltingPoint: '2128 K',
    boilingPoint: '4682 K',
    density: '6.52 g/cm³',
    yearDiscovered: '1789'
  },
  {
    number: 41,
    symbol: 'Nb',
    name: 'Niobium',
    mass: 92.906,
    category: 'transition-metal',
    group: 5,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d⁴ 5s¹',
    groupType: 'metal',
    oxidationStates: '+5, +3',
    electronegativity: 1.6,
    atomicRadius: '207 pm',
    ionizationEnergy: '6.759 eV',
    electronAffinity: '0.893 eV',
    meltingPoint: '2750 K',
    boilingPoint: '5017 K',
    density: '8.57 g/cm³',
    yearDiscovered: '1801'
  },
  {
    number: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    mass: 95.95,
    category: 'transition-metal',
    group: 6,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d⁵ 5s¹',
    groupType: 'metal',
    oxidationStates: '+6, +4',
    electronegativity: 2.16,
    atomicRadius: '209 pm',
    ionizationEnergy: '7.092 eV',
    electronAffinity: '0.746 eV',
    meltingPoint: '2896 K',
    boilingPoint: '4912 K',
    density: '10.28 g/cm³',
    yearDiscovered: '1778'
  },
  {
    number: 43,
    symbol: 'Tc',
    name: 'Technetium',
    mass: 98,
    category: 'transition-metal',
    group: 7,
    period: 5,
    state: 'Synthetic',
    config: '[Kr] 4d⁵ 5s²',
    groupType: 'metal',
    oxidationStates: '+7, +4',
    electronegativity: 1.9,
    atomicRadius: '209 pm',
    ionizationEnergy: '7.28 eV',
    electronAffinity: '0.55 eV',
    meltingPoint: '2430 K',
    boilingPoint: '4538 K',
    density: '11 g/cm³',
    yearDiscovered: '1937'
  },
  {
    number: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    mass: 101.07,
    category: 'transition-metal',
    group: 8,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d⁷ 5s¹',
    groupType: 'metal',
    oxidationStates: '+3, +4, +8',
    electronegativity: 2.2,
    atomicRadius: '207 pm',
    ionizationEnergy: '7.361 eV',
    electronAffinity: '1.05 eV',
    meltingPoint: '2607 K',
    boilingPoint: '4423 K',
    density: '12.45 g/cm³',
    yearDiscovered: '1844'
  },
  {
    number: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    mass: 102.91,
    category: 'transition-metal',
    group: 9,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d⁸ 5s¹',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 2.28,
    atomicRadius: '195 pm',
    ionizationEnergy: '7.459 eV',
    electronAffinity: '1.137 eV',
    meltingPoint: '2237 K',
    boilingPoint: '3968 K',
    density: '12.41 g/cm³',
    yearDiscovered: '1803'
  },
  {
    number: 46,
    symbol: 'Pd',
    name: 'Palladium',
    mass: 106.42,
    category: 'transition-metal',
    group: 10,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰',
    groupType: 'metal',
    oxidationStates: '+2, +4',
    electronegativity: 2.2,
    atomicRadius: '202 pm',
    ionizationEnergy: '8.337 eV',
    electronAffinity: '0.562 eV',
    meltingPoint: '1828.05 K',
    boilingPoint: '3236 K',
    density: '12.02 g/cm³',
    yearDiscovered: '1803'
  },
  {
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    mass: 107.87,
    category: 'transition-metal',
    group: 11,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 1.93,
    atomicRadius: '172 pm',
    ionizationEnergy: '7.576 eV',
    electronAffinity: '1.302 eV',
    meltingPoint: '1234.93 K',
    boilingPoint: '2435 K',
    density: '10.49 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    mass: 112.41,
    category: 'transition-metal',
    group: 12,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 1.69,
    atomicRadius: '158 pm',
    ionizationEnergy: '8.993 eV',
    electronAffinity: '-0.68 eV',
    meltingPoint: '594.22 K',
    boilingPoint: '1040 K',
    density: '8.69 g/cm³',
    yearDiscovered: '1817'
  },
  {
    number: 49,
    symbol: 'In',
    name: 'Indium',
    mass: 114.82,
    category: 'post-transition-metal',
    group: 13,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s² 5p¹',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.78,
    atomicRadius: '193 pm',
    ionizationEnergy: '5.786 eV',
    electronAffinity: '0.3 eV',
    meltingPoint: '429.75 K',
    boilingPoint: '2345 K',
    density: '7.31 g/cm³',
    yearDiscovered: '1863'
  },
  {
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    mass: 118.71,
    category: 'post-transition-metal',
    group: 14,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s² 5p²',
    groupType: 'metal',
    oxidationStates: '+4, +2',
    electronegativity: 1.96,
    atomicRadius: '217 pm',
    ionizationEnergy: '7.344 eV',
    electronAffinity: '1.2 eV',
    meltingPoint: '505.08 K',
    boilingPoint: '2875 K',
    density: '7.287 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 51,
    symbol: 'Sb',
    name: 'Antimony',
    mass: 121.76,
    category: 'metalloid',
    group: 15,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s² 5p³',
    groupType: 'metalloid',
    oxidationStates: '+5, +3, -3',
    electronegativity: 2.05,
    atomicRadius: '206 pm',
    ionizationEnergy: '8.64 eV',
    electronAffinity: '1.047 eV',
    meltingPoint: '903.78 K',
    boilingPoint: '1860 K',
    density: '6.684 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 52,
    symbol: 'Te',
    name: 'Tellurium',
    mass: 127.60,
    category: 'metalloid',
    group: 16,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s² 5p⁴',
    groupType: 'metalloid',
    oxidationStates: '+6, +4, -2',
    electronegativity: 2.1,
    atomicRadius: '206 pm',
    ionizationEnergy: '9.009 eV',
    electronAffinity: '1.971 eV',
    meltingPoint: '722.66 K',
    boilingPoint: '1261 K',
    density: '6.24 g/cm³',
    yearDiscovered: '1782'
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    mass: 126.90,
    category: 'reactive-nonmetal',
    group: 17,
    period: 5,
    state: 'Solid',
    config: '[Kr] 4d¹⁰ 5s² 5p⁵',
    groupType: 'nonmetal',
    oxidationStates: '+7, +5, +1, -1',
    electronegativity: 2.66,
    atomicRadius: '198 pm',
    ionizationEnergy: '10.451 eV',
    electronAffinity: '3.059 eV',
    meltingPoint: '386.85 K',
    boilingPoint: '457.40 K',
    density: '4.933 g/cm³',
    yearDiscovered: '1811'
  },
  {
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    mass: 131.29,
    category: 'noble-gas',
    group: 18,
    period: 5,
    state: 'Gas',
    config: '[Kr] 4d¹⁰ 5s² 5p⁶',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 2.6,
    atomicRadius: '216 pm',
    ionizationEnergy: '12.130 eV',
    electronAffinity: '-0.77 eV',
    meltingPoint: '161.40 K',
    boilingPoint: '165.03 K',
    density: '0.005887 g/cm³',
    yearDiscovered: '1898'
  },

  // --- PERIOD 6 (32 elements total: 17 main grid + 15 lanthanides) ---
  {
    number: 55,
    symbol: 'Cs',
    name: 'Caesium',
    mass: 132.91,
    category: 'alkali-metal',
    group: 1,
    period: 6,
    state: 'Solid',
    config: '[Xe] 6s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 0.79,
    atomicRadius: '343 pm',
    ionizationEnergy: '3.894 eV',
    electronAffinity: '0.472 eV',
    meltingPoint: '301.59 K',
    boilingPoint: '944 K',
    density: '1.93 g/cm³',
    yearDiscovered: '1860'
  },
  {
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    mass: 137.33,
    category: 'alkaline-earth',
    group: 2,
    period: 6,
    state: 'Solid',
    config: '[Xe] 6s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 0.89,
    atomicRadius: '268 pm',
    ionizationEnergy: '5.212 eV',
    electronAffinity: '0.145 eV',
    meltingPoint: '1000 K',
    boilingPoint: '2170 K',
    density: '3.62 g/cm³',
    yearDiscovered: '1808'
  },
  
  // Lanthanides (La-Lu)
  {
    number: 57,
    symbol: 'La',
    name: 'Lanthanum',
    mass: 138.91,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 5d¹ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.1,
    atomicRadius: '240 pm',
    ionizationEnergy: '5.577 eV',
    electronAffinity: '0.5 eV',
    meltingPoint: '1193 K',
    boilingPoint: '3737 K',
    density: '6.162 g/cm³',
    yearDiscovered: '1839'
  },
  {
    number: 58,
    symbol: 'Ce',
    name: 'Cerium',
    mass: 140.12,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹ 5d¹ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +4',
    electronegativity: 1.12,
    atomicRadius: '235 pm',
    ionizationEnergy: '5.539 eV',
    electronAffinity: '0.57 eV',
    meltingPoint: '1068 K',
    boilingPoint: '3716 K',
    density: '6.77 g/cm³',
    yearDiscovered: '1803'
  },
  {
    number: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    mass: 140.91,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f³ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +4',
    electronegativity: 1.13,
    atomicRadius: '239 pm',
    ionizationEnergy: '5.473 eV',
    electronAffinity: '0.11 eV',
    meltingPoint: '1208 K',
    boilingPoint: '3793 K',
    density: '6.77 g/cm³',
    yearDiscovered: '1885'
  },
  {
    number: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    mass: 144.24,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f⁴ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.14,
    atomicRadius: '229 pm',
    ionizationEnergy: '5.525 eV',
    electronAffinity: '0.09 eV',
    meltingPoint: '1297 K',
    boilingPoint: '3347 K',
    density: '7.01 g/cm³',
    yearDiscovered: '1885'
  },
  {
    number: 61,
    symbol: 'Pm',
    name: 'Promethium',
    mass: 145,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Synthetic',
    config: '[Xe] 4f⁵ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.13,
    atomicRadius: '236 pm',
    ionizationEnergy: '5.582 eV',
    electronAffinity: '0.13 eV',
    meltingPoint: '1315 K',
    boilingPoint: '3273 K',
    density: '7.26 g/cm³',
    yearDiscovered: '1945'
  },
  {
    number: 62,
    symbol: 'Sm',
    name: 'Samarium',
    mass: 150.36,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f⁶ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +2',
    electronegativity: 1.17,
    atomicRadius: '229 pm',
    ionizationEnergy: '5.644 eV',
    electronAffinity: '0.16 eV',
    meltingPoint: '1345 K',
    boilingPoint: '2067 K',
    density: '7.52 g/cm³',
    yearDiscovered: '1879'
  },
  {
    number: 63,
    symbol: 'Eu',
    name: 'Europium',
    mass: 151.96,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f⁷ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +2',
    electronegativity: 1.2,
    atomicRadius: '233 pm',
    ionizationEnergy: '5.670 eV',
    electronAffinity: '0.11 eV',
    meltingPoint: '1099 K',
    boilingPoint: '1802 K',
    density: '5.264 g/cm³',
    yearDiscovered: '1896'
  },
  {
    number: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    mass: 157.25,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f⁷ 5d¹ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.2,
    atomicRadius: '237 pm',
    ionizationEnergy: '5.65 eV',
    electronAffinity: '0.14 eV',
    meltingPoint: '1585 K',
    boilingPoint: '3546 K',
    density: '7.90 g/cm³',
    yearDiscovered: '1880'
  },
  {
    number: 65,
    symbol: 'Tb',
    name: 'Terbium',
    mass: 158.93,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f⁹ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +4',
    electronegativity: 1.1,
    atomicRadius: '221 pm',
    ionizationEnergy: '5.682 eV',
    electronAffinity: '1.14 eV',
    meltingPoint: '1629 K',
    boilingPoint: '3503 K',
    density: '8.23 g/cm³',
    yearDiscovered: '1843'
  },
  {
    number: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    mass: 162.50,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁰ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.22,
    atomicRadius: '228 pm',
    ionizationEnergy: '5.654 eV',
    electronAffinity: '0.35 eV',
    meltingPoint: '1680 K',
    boilingPoint: '2840 K',
    density: '8.540 g/cm³',
    yearDiscovered: '1886'
  },
  {
    number: 67,
    symbol: 'Ho',
    name: 'Holmium',
    mass: 164.93,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹¹ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.23,
    atomicRadius: '226 pm',
    ionizationEnergy: '5.698 eV',
    electronAffinity: '0.34 eV',
    meltingPoint: '1734 K',
    boilingPoint: '2993 K',
    density: '8.79 g/cm³',
    yearDiscovered: '1878'
  },
  {
    number: 68,
    symbol: 'Er',
    name: 'Erbium',
    mass: 167.26,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹² 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.24,
    atomicRadius: '226 pm',
    ionizationEnergy: '5.748 eV',
    electronAffinity: '0.31 eV',
    meltingPoint: '1802 K',
    boilingPoint: '3141 K',
    density: '9.066 g/cm³',
    yearDiscovered: '1843'
  },
  {
    number: 69,
    symbol: 'Tm',
    name: 'Thulium',
    mass: 168.93,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹³ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +2',
    electronegativity: 1.25,
    atomicRadius: '227 pm',
    ionizationEnergy: '5.81 eV',
    electronAffinity: '1.02 eV',
    meltingPoint: '1818 K',
    boilingPoint: '2223 K',
    density: '9.32 g/cm³',
    yearDiscovered: '1879'
  },
  {
    number: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    mass: 173.05,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 6s²',
    groupType: 'metal',
    oxidationStates: '+3, +2',
    electronegativity: 1.1,
    atomicRadius: '242 pm',
    ionizationEnergy: '6.254 eV',
    electronAffinity: '-0.02 eV',
    meltingPoint: '1097 K',
    boilingPoint: '1469 K',
    density: '6.90 g/cm³',
    yearDiscovered: '1878'
  },
  {
    number: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    mass: 174.97,
    category: 'lanthanide',
    group: 0,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹ 6s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.27,
    atomicRadius: '221 pm',
    ionizationEnergy: '5.426 eV',
    electronAffinity: '0.34 eV',
    meltingPoint: '1925 K',
    boilingPoint: '3675 K',
    density: '9.841 g/cm³',
    yearDiscovered: '1907'
  },

  // Transition Metals Period 6
  {
    number: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    mass: 178.49,
    category: 'transition-metal',
    group: 4,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d² 6s²',
    groupType: 'metal',
    oxidationStates: '+4',
    electronegativity: 1.3,
    atomicRadius: '212 pm',
    ionizationEnergy: '6.825 eV',
    electronAffinity: '0.178 eV',
    meltingPoint: '2506 K',
    boilingPoint: '4876 K',
    density: '13.31 g/cm³',
    yearDiscovered: '1923'
  },
  {
    number: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    mass: 180.95,
    category: 'transition-metal',
    group: 5,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d³ 6s²',
    groupType: 'metal',
    oxidationStates: '+5',
    electronegativity: 1.5,
    atomicRadius: '217 pm',
    ionizationEnergy: '7.549 eV',
    electronAffinity: '0.322 eV',
    meltingPoint: '3290 K',
    boilingPoint: '5731 K',
    density: '16.69 g/cm³',
    yearDiscovered: '1802'
  },
  {
    number: 74,
    symbol: 'W',
    name: 'Tungsten',
    mass: 183.84,
    category: 'transition-metal',
    group: 6,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    groupType: 'metal',
    oxidationStates: '+6',
    electronegativity: 2.36,
    atomicRadius: '210 pm',
    ionizationEnergy: '7.864 eV',
    electronAffinity: '0.816 eV',
    meltingPoint: '3695 K',
    boilingPoint: '5828 K',
    density: '19.25 g/cm³',
    yearDiscovered: '1783'
  },
  {
    number: 75,
    symbol: 'Re',
    name: 'Rhenium',
    mass: 186.21,
    category: 'transition-metal',
    group: 7,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    groupType: 'metal',
    oxidationStates: '+7, +6, +4',
    electronegativity: 1.9,
    atomicRadius: '217 pm',
    ionizationEnergy: '7.88 eV',
    electronAffinity: '0.15 eV',
    meltingPoint: '3459 K',
    boilingPoint: '5869 K',
    density: '21.02 g/cm³',
    yearDiscovered: '1925'
  },
  {
    number: 76,
    symbol: 'Os',
    name: 'Osmium',
    mass: 190.23,
    category: 'transition-metal',
    group: 8,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    groupType: 'metal',
    oxidationStates: '+4, +3, +8',
    electronegativity: 2.2,
    atomicRadius: '216 pm',
    ionizationEnergy: '8.438 eV',
    electronAffinity: '1.1 eV',
    meltingPoint: '3306 K',
    boilingPoint: '5285 K',
    density: '22.59 g/cm³',
    yearDiscovered: '1803'
  },
  {
    number: 77,
    symbol: 'Ir',
    name: 'Iridium',
    mass: 192.22,
    category: 'transition-metal',
    group: 9,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    groupType: 'metal',
    oxidationStates: '+4, +3, +1',
    electronegativity: 2.2,
    atomicRadius: '202 pm',
    ionizationEnergy: '8.967 eV',
    electronAffinity: '1.565 eV',
    meltingPoint: '2739 K',
    boilingPoint: '4701 K',
    density: '22.56 g/cm³',
    yearDiscovered: '1803'
  },
  {
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    mass: 195.08,
    category: 'transition-metal',
    group: 10,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    groupType: 'metal',
    oxidationStates: '+4, +2',
    electronegativity: 2.28,
    atomicRadius: '209 pm',
    ionizationEnergy: '8.958 eV',
    electronAffinity: '2.125 eV',
    meltingPoint: '2041.40 K',
    boilingPoint: '4098 K',
    density: '21.45 g/cm³',
    yearDiscovered: '1735'
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    mass: 196.97,
    category: 'transition-metal',
    group: 11,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    groupType: 'metal',
    oxidationStates: '+3, +1',
    electronegativity: 2.54,
    atomicRadius: '166 pm',
    ionizationEnergy: '9.225 eV',
    electronAffinity: '2.308 eV',
    meltingPoint: '1337.33 K',
    boilingPoint: '3129 K',
    density: '19.3 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    mass: 200.59,
    category: 'transition-metal',
    group: 12,
    period: 6,
    state: 'Liquid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    groupType: 'metal',
    oxidationStates: '+2, +1',
    electronegativity: 2.0,
    atomicRadius: '155 pm',
    ionizationEnergy: '10.437 eV',
    electronAffinity: '-0.5 eV',
    meltingPoint: '234.32 K',
    boilingPoint: '629.88 K',
    density: '13.534 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 81,
    symbol: 'Tl',
    name: 'Thallium',
    mass: 204.38,
    category: 'post-transition-metal',
    group: 13,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    groupType: 'metal',
    oxidationStates: '+1, +3',
    electronegativity: 1.62,
    atomicRadius: '196 pm',
    ionizationEnergy: '6.108 eV',
    electronAffinity: '0.377 eV',
    meltingPoint: '577 K',
    boilingPoint: '1746 K',
    density: '11.85 g/cm³',
    yearDiscovered: '1861'
  },
  {
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    mass: 207.2,
    category: 'post-transition-metal',
    group: 14,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    groupType: 'metal',
    oxidationStates: '+2, +4',
    electronegativity: 2.33,
    atomicRadius: '202 pm',
    ionizationEnergy: '7.416 eV',
    electronAffinity: '0.356 eV',
    meltingPoint: '600.61 K',
    boilingPoint: '2022 K',
    density: '11.34 g/cm³',
    yearDiscovered: 'Ancient'
  },
  {
    number: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    mass: 208.98,
    category: 'post-transition-metal',
    group: 15,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    groupType: 'metal',
    oxidationStates: '+3, +5',
    electronegativity: 2.02,
    atomicRadius: '207 pm',
    ionizationEnergy: '7.289 eV',
    electronAffinity: '0.946 eV',
    meltingPoint: '544.70 K',
    boilingPoint: '1837 K',
    density: '9.78 g/cm³',
    yearDiscovered: '1753'
  },
  {
    number: 84,
    symbol: 'Po',
    name: 'Polonium',
    mass: 209,
    category: 'post-transition-metal',
    group: 16,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    groupType: 'metal',
    oxidationStates: '+4, +2',
    electronegativity: 2.0,
    atomicRadius: '197 pm',
    ionizationEnergy: '8.417 eV',
    electronAffinity: '1.9 eV',
    meltingPoint: '527 K',
    boilingPoint: '1235 K',
    density: '9.196 g/cm³',
    yearDiscovered: '1898'
  },
  {
    number: 85,
    symbol: 'At',
    name: 'Astatine',
    mass: 210,
    category: 'metalloid',
    group: 17,
    period: 6,
    state: 'Solid',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    groupType: 'metalloid',
    oxidationStates: '+1, -1',
    electronegativity: 2.2,
    atomicRadius: '202 pm',
    ionizationEnergy: '9.3 eV',
    electronAffinity: '2.8 eV',
    meltingPoint: '575 K',
    boilingPoint: '610 K',
    density: '7.2 g/cm³',
    yearDiscovered: '1940'
  },
  {
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    mass: 222,
    category: 'noble-gas',
    group: 18,
    period: 6,
    state: 'Gas',
    config: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 2.2,
    atomicRadius: '220 pm',
    ionizationEnergy: '10.748 eV',
    electronAffinity: '-0.85 eV',
    meltingPoint: '202 K',
    boilingPoint: '211.30 K',
    density: '0.00973 g/cm³',
    yearDiscovered: '1900'
  },

  // --- PERIOD 7 (32 elements total: 17 main grid + 15 actinides) ---
  {
    number: 87,
    symbol: 'Fr',
    name: 'Francium',
    mass: 223,
    category: 'alkali-metal',
    group: 1,
    period: 7,
    state: 'Solid',
    config: '[Rn] 7s¹',
    groupType: 'metal',
    oxidationStates: '+1',
    electronegativity: 0.79,
    atomicRadius: '348 pm',
    ionizationEnergy: '4.072 eV',
    electronAffinity: '0.47 eV',
    meltingPoint: '300 K',
    boilingPoint: '950 K',
    density: '2.48 g/cm³',
    yearDiscovered: '1939'
  },
  {
    number: 88,
    symbol: 'Ra',
    name: 'Radium',
    mass: 226,
    category: 'alkaline-earth',
    group: 2,
    period: 7,
    state: 'Solid',
    config: '[Rn] 7s²',
    groupType: 'metal',
    oxidationStates: '+2',
    electronegativity: 0.9,
    atomicRadius: '283 pm',
    ionizationEnergy: '5.278 eV',
    electronAffinity: '0.11 eV',
    meltingPoint: '973 K',
    boilingPoint: '2010 K',
    density: '5.5 g/cm³',
    yearDiscovered: '1898'
  },

  // Actinides (Ac-Lr)
  {
    number: 89,
    symbol: 'Ac',
    name: 'Actinium',
    mass: 227,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 6d¹ 7s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.1,
    atomicRadius: '260 pm',
    ionizationEnergy: '5.17 eV',
    electronAffinity: '0.3 eV',
    meltingPoint: '1323 K',
    boilingPoint: '3471 K',
    density: '10.07 g/cm³',
    yearDiscovered: '1899'
  },
  {
    number: 90,
    symbol: 'Th',
    name: 'Thorium',
    mass: 232.04,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 6d² 7s²',
    groupType: 'metal',
    oxidationStates: '+4',
    electronegativity: 1.3,
    atomicRadius: '237 pm',
    ionizationEnergy: '6.3 eV',
    electronAffinity: '1.13 eV',
    meltingPoint: '2023 K',
    boilingPoint: '5061 K',
    density: '11.72 g/cm³',
    yearDiscovered: '1828'
  },
  {
    number: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    mass: 231.04,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f² 6d¹ 7s²',
    groupType: 'metal',
    oxidationStates: '+5, +4',
    electronegativity: 1.5,
    atomicRadius: '221 pm',
    ionizationEnergy: '5.89 eV',
    electronAffinity: '0.12 eV',
    meltingPoint: '1841 K',
    boilingPoint: '4300 K',
    density: '15.37 g/cm³',
    yearDiscovered: '1913'
  },
  {
    number: 92,
    symbol: 'U',
    name: 'Uranium',
    mass: 238.03,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f³ 6d¹ 7s²',
    groupType: 'metal',
    oxidationStates: '+6, +4',
    electronegativity: 1.38,
    atomicRadius: '186 pm',
    ionizationEnergy: '6.194 eV',
    electronAffinity: '0.3 eV',
    meltingPoint: '1405.30 K',
    boilingPoint: '4404 K',
    density: '18.95 g/cm³',
    yearDiscovered: '1789'
  },
  {
    number: 93,
    symbol: 'Np',
    name: 'Neptunium',
    mass: 237,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f⁴ 6d¹ 7s²',
    groupType: 'metal',
    oxidationStates: '+5, +6, +4, +3',
    electronegativity: 1.36,
    atomicRadius: '221 pm',
    ionizationEnergy: '6.265 eV',
    electronAffinity: '0.45 eV',
    meltingPoint: '917 K',
    boilingPoint: '4175 K',
    density: '20.25 g/cm³',
    yearDiscovered: '1940'
  },
  {
    number: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    mass: 244,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f⁶ 7s²',
    groupType: 'metal',
    oxidationStates: '+4, +3, +6',
    electronegativity: 1.28,
    atomicRadius: '242 pm',
    ionizationEnergy: '6.026 eV',
    electronAffinity: '-0.48 eV',
    meltingPoint: '912.50 K',
    boilingPoint: '3501 K',
    density: '19.84 g/cm³',
    yearDiscovered: '1940'
  },
  {
    number: 95,
    symbol: 'Am',
    name: 'Americium',
    mass: 243,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f⁷ 7s²',
    groupType: 'metal',
    oxidationStates: '+3, +4',
    electronegativity: 1.3,
    atomicRadius: '244 pm',
    ionizationEnergy: '5.973 eV',
    electronAffinity: '0.11 eV',
    meltingPoint: '1449 K',
    boilingPoint: '2880 K',
    density: '13.67 g/cm³',
    yearDiscovered: '1944'
  },
  {
    number: 96,
    symbol: 'Cm',
    name: 'Curium',
    mass: 247,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f⁷ 6d¹ 7s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.3,
    atomicRadius: '245 pm',
    ionizationEnergy: '5.991 eV',
    electronAffinity: '0.22 eV',
    meltingPoint: '1613 K',
    boilingPoint: '3383 K',
    density: '13.51 g/cm³',
    yearDiscovered: '1944'
  },
  {
    number: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    mass: 247,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f⁹ 7s²',
    groupType: 'metal',
    oxidationStates: '+3, +4',
    electronegativity: 1.3,
    atomicRadius: '244 pm',
    ionizationEnergy: '6.197 eV',
    electronAffinity: '0.24 eV',
    meltingPoint: '1259 K',
    boilingPoint: '2900 K',
    density: '14.78 g/cm³',
    yearDiscovered: '1949'
  },
  {
    number: 98,
    symbol: 'Cf',
    name: 'Californium',
    mass: 251,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f¹⁰ 7s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.3,
    atomicRadius: '245 pm',
    ionizationEnergy: '6.281 eV',
    electronAffinity: '0.25 eV',
    meltingPoint: '1173 K',
    boilingPoint: '1743 K',
    density: '15.1 g/cm³',
    yearDiscovered: '1950'
  },
  {
    number: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    mass: 252,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Solid',
    config: '[Rn] 5f¹¹ 7s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.3,
    atomicRadius: '245 pm',
    ionizationEnergy: '6.42 eV',
    electronAffinity: '0.29 eV',
    meltingPoint: '1133 K',
    boilingPoint: '1269 K',
    density: '8.84 g/cm³',
    yearDiscovered: '1952'
  },
  {
    number: 100,
    symbol: 'Fm',
    name: 'Fermium',
    mass: 257,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹² 7s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.3,
    atomicRadius: '245 pm',
    ionizationEnergy: '6.50 eV',
    electronAffinity: '0.33 eV',
    meltingPoint: '1800 K',
    boilingPoint: 'N/A',
    density: 'N/A',
    yearDiscovered: '1952'
  },
  {
    number: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    mass: 258,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹³ 7s²',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.3,
    atomicRadius: '246 pm',
    ionizationEnergy: '6.58 eV',
    electronAffinity: '0.97 eV',
    meltingPoint: '1100 K',
    boilingPoint: 'N/A',
    density: 'N/A',
    yearDiscovered: '1955'
  },
  {
    number: 102,
    symbol: 'No',
    name: 'Nobelium',
    mass: 259,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 7s²',
    groupType: 'metal',
    oxidationStates: '+3, +2',
    electronegativity: 1.3,
    atomicRadius: '246 pm',
    ionizationEnergy: '6.65 eV',
    electronAffinity: '2.23 eV',
    meltingPoint: '1100 K',
    boilingPoint: 'N/A',
    density: 'N/A',
    yearDiscovered: '1966'
  },
  {
    number: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    mass: 266,
    category: 'actinide',
    group: 0,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 7s² 7p¹',
    groupType: 'metal',
    oxidationStates: '+3',
    electronegativity: 1.3,
    atomicRadius: '246 pm',
    ionizationEnergy: '4.9 eV',
    electronAffinity: '-0.3 eV',
    meltingPoint: '1900 K',
    boilingPoint: 'N/A',
    density: 'N/A',
    yearDiscovered: '1961'
  },

  // Post-Actinide Superheavy synthetic elements
  {
    number: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    mass: 267,
    category: 'synthetic',
    group: 4,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d² 7s²',
    groupType: 'metal',
    oxidationStates: '+4',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: '6.0 eV',
    electronAffinity: 'N/A',
    meltingPoint: '2400 K',
    boilingPoint: '5800 K',
    density: '23.2 g/cm³',
    yearDiscovered: '1964'
  },
  {
    number: 105,
    symbol: 'Db',
    name: 'Dubnium',
    mass: 268,
    category: 'synthetic',
    group: 5,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d³ 7s²',
    groupType: 'metal',
    oxidationStates: '+5',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: '2600 K',
    boilingPoint: 'N/A',
    density: '29.3 g/cm³',
    yearDiscovered: '1967'
  },
  {
    number: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    mass: 269,
    category: 'synthetic',
    group: 6,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d⁴ 7s²',
    groupType: 'metal',
    oxidationStates: '+6',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '35.0 g/cm³',
    yearDiscovered: '1974'
  },
  {
    number: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    mass: 270,
    category: 'synthetic',
    group: 7,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d⁵ 7s²',
    groupType: 'metal',
    oxidationStates: '+7',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '37.1 g/cm³',
    yearDiscovered: '1981'
  },
  {
    number: 108,
    symbol: 'Hs',
    name: 'Hassium',
    mass: 277,
    category: 'synthetic',
    group: 8,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d⁶ 7s²',
    groupType: 'metal',
    oxidationStates: '+8',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '40.7 g/cm³',
    yearDiscovered: '1984'
  },
  {
    number: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    mass: 278,
    category: 'synthetic',
    group: 9,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d⁷ 7s²',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '37.4 g/cm³',
    yearDiscovered: '1982'
  },
  {
    number: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    mass: 281,
    category: 'synthetic',
    group: 10,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d⁸ 7s²',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '34.8 g/cm³',
    yearDiscovered: '1994'
  },
  {
    number: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    mass: 282,
    category: 'synthetic',
    group: 11,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d⁹ 7s²',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '28.7 g/cm³',
    yearDiscovered: '1994'
  },
  {
    number: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    mass: 285,
    category: 'synthetic',
    group: 12,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '23.7 g/cm³',
    yearDiscovered: '1996'
  },
  {
    number: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    mass: 286,
    category: 'synthetic',
    group: 13,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '16 g/cm³',
    yearDiscovered: '2004'
  },
  {
    number: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    mass: 289,
    category: 'synthetic',
    group: 14,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '14 g/cm³',
    yearDiscovered: '1998'
  },
  {
    number: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    mass: 290,
    category: 'synthetic',
    group: 15,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '13.5 g/cm³',
    yearDiscovered: '2003'
  },
  {
    number: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    mass: 293,
    category: 'synthetic',
    group: 16,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    groupType: 'metal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '12.9 g/cm³',
    yearDiscovered: '2000'
  },
  {
    number: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    mass: 294,
    category: 'synthetic',
    group: 17,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    groupType: 'nonmetal',
    oxidationStates: 'N/A',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '7.2 g/cm³',
    yearDiscovered: '2010'
  },
  {
    number: 118,
    symbol: 'Og',
    name: 'Oganesson',
    mass: 294,
    category: 'synthetic',
    group: 18,
    period: 7,
    state: 'Synthetic',
    config: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    groupType: 'nonmetal',
    oxidationStates: '0',
    electronegativity: 1.3,
    atomicRadius: '250 pm',
    ionizationEnergy: 'N/A',
    electronAffinity: 'N/A',
    meltingPoint: 'N/A',
    boilingPoint: 'N/A',
    density: '7.0 g/cm³',
    yearDiscovered: '2002'
  }
];

export const CATEGORIES_LABELS: Record<string, { label: string; color: string }> = {
  'reactive-nonmetal': { label: 'Nonmetals', color: 'bg-emerald-200 border-emerald-500 text-emerald-950 hover:bg-emerald-300 font-extrabold' },
  'noble-gas': { label: 'Noble Gases', color: 'bg-purple-200 border-purple-500 text-purple-950 hover:bg-purple-300 font-extrabold' },
  'alkali-metal': { label: 'Alkali Metals', color: 'bg-rose-200 border-rose-500 text-rose-950 hover:bg-rose-300 font-extrabold' },
  'alkaline-earth': { label: 'Alkaline Earth', color: 'bg-amber-200 border-amber-500 text-amber-950 hover:bg-amber-300 font-extrabold' },
  'metalloid': { label: 'Metalloids', color: 'bg-yellow-200 border-yellow-500 text-yellow-950 hover:bg-yellow-300 font-extrabold' },
  'post-transition-metal': { label: 'Post-Transition', color: 'bg-blue-200 border-blue-500 text-blue-950 hover:bg-blue-300 font-extrabold' },
  'transition-metal': { label: 'Transition Metals', color: 'bg-sky-150 border-sky-400 text-sky-950 hover:bg-sky-250 font-extrabold' },
  'lanthanide': { label: 'Lanthanides', color: 'bg-pink-150 border-pink-400 text-pink-950 hover:bg-pink-250 font-extrabold' },
  'actinide': { label: 'Actinides', color: 'bg-fuchsia-200 border-fuchsia-500 text-fuchsia-950 hover:bg-fuchsia-300 font-extrabold' },
  'synthetic': { label: 'Synthetic', color: 'bg-slate-200 border-slate-500 text-slate-950 hover:bg-slate-300 font-extrabold' }
};
